# Generated by Django 5.1.2 on 2025-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                ("platform", models.CharField(max_length=100)),
                ("master_category_name", models.CharField(max_length=12)),
                ("small_category_name", models.IntegerField()),
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("img_url", models.URLField(max_length=1000)),
                ("product_name", models.CharField(max_length=100)),
                ("brand_name_kr", models.CharField(max_length=100)),
                ("brand_name_en", models.CharField(max_length=100)),
                ("original_price", models.IntegerField()),
                ("final_price", models.IntegerField()),
                ("discount_ratio", models.IntegerField()),
                ("review_counting", models.IntegerField()),
                ("review_avg_rating", models.FloatField()),
                ("like_counting", models.IntegerField()),
                ("created_at", models.DateField()),
            ],
            options={
                "db_table": "retail_silver_layer.product_detail_tb",
                "managed": False,
            },
        ),
    ]
