# Generated by Django 5.1.2 on 2025-01-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retailapp", "0002_productdetail"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productdetail",
            table='"retail_silver_layer"."product_detail_tb"',
        ),
    ]
